FROM node:lts-slim AS production

WORKDIR /app

COPY ./packages/next/.next ./.next
COPY ./packages/next/public ./public
COPY ./packages/next/package.json ./package.json
COPY ./packages/next/node_modules ./node_modules

ENV NODE_ENV production

EXPOSE 7400

CMD ["npm", "start"]
