// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/song/:id/info": {
    params: {
      "id": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/song/:id/info";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/song/[id]/info.tsx": {
    id: "routes/song/[id]/info";
    page: "/song/:id/info";
  };
};